# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Infoblox Inc.

"""Parametrized sweep hitting the `if ctx.client is None: … return` early-exit
branch on every command handler across all modules. Each command should either
print "Not connected" or "No grid" / "Not yet implemented" - all acceptable
early-exit markers. This covers ~150 otherwise-untested lines at once.
"""

from __future__ import annotations

import pytest

import ibcli.commands  # noqa: F401 - registers all command trees
from ibcli.context import Context
from ibcli.dispatcher import process_line

_EARLY_EXIT_MARKERS = (
    "Not connected",
    "No grid",
    "Not yet implemented",
    "Unknown command",
    "Unknown argument",
    "Error:",
    "Incomplete",
    "OK:",
    "^---",
    "Ambiguous",
    "No network",
    "No ",
)


_COMMANDS = [
    # Zone / DNS
    "configure zone add probe.example.com",
    "configure zone probe.example.com modify comment=x",
    "configure zone probe.example.com delete",
    "configure zone probe.example.com add host web01 10.0.0.1",
    "configure zone probe.example.com delete host web01",
    "configure zone probe.example.com modify host web01 add-alias=x",
    "configure zone probe.example.com rename host web01 web-prod01",
    "configure zone probe.example.com dnssec sign",
    "configure zone probe.example.com dnssec unsign",
    "configure zone probe.example.com dnssec rollover_ksk",
    "configure zone probe.example.com dnssec rollover_zsk",
    "configure zone probe.example.com copy from other.example.com",
    "configure zone probe.example.com add a web 10.0.0.1",
    "configure zone probe.example.com add aaaa web 2001:db8::1",
    "configure zone probe.example.com add cname www web",
    "configure zone probe.example.com add mx mail mail.probe.example.com 10",
    "configure zone probe.example.com add txt spf v=spf1",
    "configure zone probe.example.com add ptr 10.0.0.1 web.probe.example.com",
    "configure zone probe.example.com delete a web",
    # Views / NS groups / SRGs
    "configure view add External",
    "configure view External delete",
    "configure nsgroup add ns1 primary=gm.example.com",
    "configure nsgroup ns1 delete",
    "configure shared_record_group add srg-a",
    "configure shared_record_group srg-a delete",
    # Shared records
    "configure shared_record a add www 10.0.0.1 group=srg-a",
    "configure shared_record a delete www group=srg-a",
    "configure shared_record aaaa add www 2001:db8::1 group=srg-a",
    "configure shared_record cname add portal www group=srg-a",
    "configure shared_record mx add mail mail.example.com 10 group=srg-a",
    "configure shared_record txt add spf v=spf1 group=srg-a",
    # Networks / ranges / fixed
    "configure network add 10.0.0.0/24",
    "configure network 10.0.0.0/24 modify comment=x",
    "configure network 10.0.0.0/24 delete",
    "configure network 10.0.0.0/24 range add 10.0.0.10 10.0.0.20",
    "configure network 10.0.0.0/24 range modify 10.0.0.10 10.0.0.20 failover=fo1",
    "configure network 10.0.0.0/24 range delete 10.0.0.10 10.0.0.20",
    "configure network 10.0.0.0/24 fixed add 10.0.0.5 aa:bb:cc:00:00:01",
    "configure network 10.0.0.0/24 fixed delete 10.0.0.5",
    "configure network 10.0.0.0/24 extattrs set EA1 v1",
    "configure network 10.0.0.0/24 extattrs delete EA1",
    "configure network failover add fo1 primary ibdhcp01 secondary ibdhcp02",
    "configure network failover fo1 delete",
    # DHCP filters
    "configure network macfilter add macfilt1",
    "configure network macfilter delete macfilt1",
    "configure network filter macfilt1 add macaddress aa:bb:cc:00:00:01",
    "configure network filter macfilt1 delete macaddress aa:bb:cc:00:00:01",
    # DTC
    "configure dtc server add web1 host=10.0.0.1",
    "configure dtc server web1 delete",
    "configure dtc server web1 set comment=x",
    "configure dtc pool add p1",
    "configure dtc pool p1 delete",
    "configure dtc pool p1 set comment=x",
    "configure dtc pool p1 server add web1",
    "configure dtc pool p1 server delete web1",
    "configure dtc pool p1 monitor add http mon1",
    "configure dtc pool p1 monitor delete http mon1",
    "configure dtc lbdn add lb1",
    "configure dtc lbdn lb1 delete",
    "configure dtc lbdn lb1 set comment=x",
    "configure dtc lbdn lb1 pool add p1",
    "configure dtc lbdn lb1 pool delete p1",
    "configure dtc monitor http add mon1",
    "configure dtc monitor http mon1 delete",
    "configure dtc monitor icmp add mon1",
    "configure dtc monitor tcp add mon1",
    "configure dtc topology add t1",
    "configure dtc topology t1 delete",
    # RPZ
    "configure rpz zone add rpz.example.com policy=GIVEN",
    "configure rpz zone rpz.example.com delete",
    "configure rpz record a add bad.example.com.rpz.example.com 127.0.0.1 zone rpz.example.com",
    # Auth
    "configure auth ldap add lab-ldap",
    "configure auth ldap lab-ldap delete",
    "configure auth ldap lab-ldap set key=value",
    "configure auth ad add lab-ad",
    "configure auth ad lab-ad delete",
    "configure auth ad lab-ad set key=value",
    "configure auth radius add lab-radius",
    "configure auth radius lab-radius delete",
    "configure auth radius lab-radius set key=value",
    "configure auth tacacs add lab-tacacs",
    "configure auth saml add lab-saml",
    "configure auth certificate add lab-cert",
    # Admin
    "configure admin user add alice password=x",
    "configure admin user alice delete",
    "configure admin group add lab-netops",
    "configure admin group lab-netops delete",
    "configure admin role add lab-operator",
    "configure admin role lab-operator delete",
    "configure admin permission add role=lab-operator object=networks write",
    # Files
    "upload csv /tmp/x.csv",
    "upload database /tmp/x.tar.gz",
    "upload leases /tmp/x.txt",
    "download csv /tmp/x.csv object record:host",
    "download database /tmp/x.tar.gz",
    "download log_files /tmp/x syslog",
    "download lease_history /tmp/x.csv",
    "download support_bundle /tmp/x.tar.gz",
    "download merge_log /tmp/x.log",
    "download dns_conf /tmp/x.cfg member gm.example.com",
    "download dns_cache /tmp/x.cache member gm.example.com",
    "download dhcp_conf /tmp/x.cfg member gm.example.com",
    # Grid + members
    "configure grid Migration member add m1.example.com",
    "configure grid Migration member m1.example.com delete",
    "configure grid Migration member m1.example.com modify comment=x",
    "configure grid Migration member m1.example.com dns enable",
    "configure grid Migration member m1.example.com dhcp enable",
    "configure grid Migration member m1.example.com dhcp enable both",
    "configure grid Migration member m1.example.com anycast add 192.0.2.1",
    "configure grid Migration member m1.example.com anycast delete 192.0.2.1",
    "configure grid Migration dns set dnssec_enabled=True",
    "configure grid Migration dns allow_recursion any",
    # ACLs / EAs
    "configure acl add acl1 access_list=10.0.0.0/8",
    "configure acl acl1 delete",
    "configure acl acl1 modify comment=x",
    'configure grid attribute add "DC Location" type string',
    # show commands (many also check ctx.client)
    "show grid",
    "show member",
    "show zone probe.example.com",
    "show record host web01.probe.example.com",
    "show network 10.0.0.0/24",
    "show range",
    "show fixed",
    "show lease",
    "show dtc",
    "show dtc server",
    "show dtc pool",
    "show dtc lbdn",
    "show address 10.0.0.1",
    "show auth ldap",
    "show auth ad",
    "show auth radius",
    "show admin user",
    "show admin role",
    "show admin group",
    "show view",
    "show nsgroup",
    "show rpz zone",
    # Modern record types (zone_modern.py)
    "configure record caa add svc.example.com 0 issue letsencrypt.org",
    "configure record caa delete svc.example.com",
    "show record caa",
    "show record caa svc.example.com",
    "configure record dname add sub.example.com target.example.com",
    "configure record dname delete sub.example.com",
    "show record dname",
    "show record dname sub.example.com",
    "configure record alias add a.example.com t.example.com",
    "configure record alias delete a.example.com",
    "show record alias",
    "show record alias a.example.com",
    "configure record ns add example.com ns1.example.com",
    "configure record ns delete example.com",
    "show record ns",
    "show record ns example.com",
    "configure record naptr add svc.example.com",
    "configure record naptr delete svc.example.com",
    "show record naptr",
    "show record naptr svc.example.com",
    "configure record tlsa add svc.example.com",
    "configure record tlsa delete svc.example.com",
    "show record tlsa",
    "show record tlsa svc.example.com",
    "configure record https add svc.example.com 1 target.example.com",
    "configure record https delete svc.example.com",
    "show record https",
    "show record https svc.example.com",
    "configure record svcb add svc.example.com 1 target.example.com",
    "configure record svcb delete svc.example.com",
    "show record svcb",
    "show record svcb svc.example.com",
    "configure shared_record a add www 10.0.0.1 group=srg-a",
    "configure shared_record a delete www group=srg-a",
    "show shared_record a",
    "show shared_record a group srg-a",
    "configure shared_record aaaa add www 2001:db8::1 group=srg-a",
    "configure shared_record aaaa delete www group=srg-a",
    "show shared_record aaaa",
    "show shared_record aaaa group srg-a",
    "configure shared_record cname add www target.example.com group=srg-a",
    "configure shared_record cname delete www group=srg-a",
    "show shared_record cname",
    "show shared_record cname group srg-a",
    "configure shared_record mx add mail mail.example.com 10 group=srg-a",
    "configure shared_record mx delete mail group=srg-a",
    "show shared_record mx",
    "show shared_record mx group srg-a",
    "configure shared_record txt add spf v=spf1 group=srg-a",
    "configure shared_record txt delete spf group=srg-a",
    "show shared_record txt",
    "show shared_record txt group srg-a",
    "configure shared_record srv add svc 1 1 80 target.example.com group=srg-a",
    "configure shared_record srv delete svc group=srg-a",
    "show shared_record srv",
    "show shared_record srv group srg-a",
    # IPv6 networks / ranges / fixed
    "configure network add 2001:db8::/64",
    "configure network 2001:db8::/64 delete",
    "configure network 2001:db8::/64 modify comment=x",
    "configure network 2001:db8::/64 range add 2001:db8::10 2001:db8::20",
    "configure network 2001:db8::/64 range delete 2001:db8::10 2001:db8::20",
    "configure network 2001:db8::/64 fixed add 2001:db8::5 00:11:22:33:44:55",
    "configure network 2001:db8::/64 fixed delete 2001:db8::5",
    "show network 2001:db8::/64",
    "show network ipv6",
    "show network container",
    "show network container 10.0.0.0/16",
    # DHCP ranges/options
    "configure network 10.0.0.0/24 option add routers 10.0.0.1",
    "configure network 10.0.0.0/24 option delete routers",
    "configure network 10.0.0.0/24 member add m1.example.com",
    "configure network 10.0.0.0/24 member delete m1.example.com",
    "show option",
    "show rangetemplate",
    "show networktemplate",
    # Grid extensions
    "configure grid Migration dhcp set lease_logging_enabled=true",
    "configure grid Migration ntp add 10.0.0.1",
    "configure grid Migration ntp delete 10.0.0.1",
    "configure grid Migration snmp add community public",
    "configure grid Migration snmp delete community public",
    "configure grid Migration syslog add 10.0.0.1",
    "configure grid Migration syslog delete 10.0.0.1",
    "configure grid Migration member m1.example.com ntp add 10.0.0.1",
    "configure grid Migration member m1.example.com ntp delete 10.0.0.1",
    "configure grid Migration member m1.example.com syslog add 10.0.0.1",
    "configure grid Migration member m1.example.com syslog delete 10.0.0.1",
    "show grid dns",
    "show grid dhcp",
    "show member dns",
    "show member dhcp",
    # Notifications / threat / discovery
    "configure notify endpoint add ep1 uri=https://x",
    "configure notify endpoint ep1 delete",
    "configure notify rule add r1 endpoint=ep1",
    "configure notify rule r1 delete",
    "show notify endpoint",
    "show notify rule",
    "show threat protection",
    "show threat analytics",
    "show threat insight",
    "configure discovery add disc1",
    "configure discovery disc1 delete",
    "show discovery",
    # Upgrade / ops / server / system / template
    "show upgrade status",
    "show upgrade group",
    "configure upgrade group add grp1",
    "configure upgrade group grp1 delete",
    "show certificate",
    "configure certificate generate cn=host.example.com",
    "show ea definition",
    "configure ea definition add MyEA type=string",
    "configure ea definition MyEA delete",
    "show template network",
    "show template range",
    "configure template network add tmpl1",
    "configure template network tmpl1 delete",
    # RPZ extended
    "configure rpz record cname add bad.example.com.rpz.example.com target.example.com zone rpz.example.com",
    "configure rpz record txt add bad.example.com.rpz.example.com data zone rpz.example.com",
    "configure rpz record ipaddress add 10.0.0.1 zone rpz.example.com",
    "show rpz record",
    "show rpz record a zone rpz.example.com",
    # Auth extended
    "show auth saml",
    "show auth tacacs",
    "show auth certificate",
    "configure auth saml lab-saml delete",
    "configure auth saml lab-saml set key=value",
    "configure auth tacacs lab-tacacs delete",
    "configure auth tacacs lab-tacacs set key=value",
    "configure auth certificate lab-cert delete",
    "configure auth certificate lab-cert set key=value",
]


@pytest.mark.parametrize("cmd", _COMMANDS)
async def test_command_early_exits_cleanly(cmd, capsys):
    """Each command either prints an early-exit marker or is a no-op -
    never a traceback or unhandled exception."""
    ctx = Context()  # client=None
    await process_line(cmd, ctx)
    out = capsys.readouterr().out
    # Some commands may silently no-op (e.g. malformed line regex); accept
    # that too. The real assertion is "no traceback" (if it raised, the
    # test would have failed).
    if out.strip():
        assert any(marker in out for marker in _EARLY_EXIT_MARKERS), (
            f"Command {cmd!r} produced unexpected output: {out!r}"
        )
